spring:
  application:
    name: taskManager
  datasource:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    enabled: false
  security:
    user:
      name: ${SECURITY_USER}
      password: ${SECURITY_PASSWORD}